// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AudioPlayerController from "./audio_player_controller"
application.register("audio-player", AudioPlayerController)

import DebounceController from "./debounce_controller"
application.register("debounce", DebounceController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import PodcastFormController from "./podcast_form_controller"
application.register("podcast-form", PodcastFormController)

import ProfileEditFormController from "./profile_edit_form_controller"
application.register("profile-edit-form", ProfileEditFormController)

import RatingController from "./rating_controller"
application.register("rating", RatingController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
