// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// Use the correct import based on the actual package export
import NotificationController from "@stimulus-components/notification"

application.register("notification", NotificationController)
